apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-repset2
spec:
  replicas: 2
  selector:
    matchLabels:
      pod-is-for: garbage-collection-example2
  template:
    metadata:
      labels:
        pod-is-for: garbage-collection-example2
    spec:
      containers:
      - name: nginx
        image: nginx
