apiVersion: v1
kind: Pod
metadata:
  name: test-agnhost
  labels:
    environment: test
spec:
  containers:
  #- args: ["fake-gitserver"]
  - args:
    - pause
    #image: gcr.io/kubernetes-e2e-test-images/agnhost:2.2
    image: jungler/agnhost:2.4
    name: agnhost
    ports:
      - containerPort: 8000
    imagePullPolicy: IfNotPresent
