apiVersion: v1
kind: Service
metadata:
  labels:
    test: webhook
  name: test-gitclone
spec:
  selector:
    environment: test
  ports:
  - port: 2345
  #- port: 440
    protocol: TCP
    #name: http-portal
    targetPort: 8000
    nodePort: 30000
  sessionAffinity: None
  type: NodePort
  #type: ClusterIP
